/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package culminating.project;

/**
 *
 * @author blhad3491
 */

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

public class questionPage extends javax.swing.JFrame {

    public void closePage() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);// this is the line of code that will close the page
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);// this is accessing the tool kit to be able to close the page
    }
     
    int quesNum = 1;
    int score = 0;
    public String ScoreCount = "Score: " + score;
     
    public void startUp() {
        scoreLabel.setText("Score: " + score);
        ans1Label.setText(arrayAnsSet1[0]);
        ans4Label.setText(arrayAnsSet1[1]);
        ans9Label.setText(arrayAnsSet1[2]); 
    }
    
    public void clearLabels() {
        ans1Label.setText("");
        ans2Label.setText("");
        ans3Label.setText("");
        ans4Label.setText("");
        ans5Label.setText("");
        ans6Label.setText("");
        ans7Label.setText("");
        ans8Label.setText("");
        ans9Label.setText("");
        outputLabel.setText("");
    }
    
    String[] arrayAnsSet1 = new String[3]; 
    String[] arrayAnsSet2 = new String[4]; 
    String[] arrayAnsSet3 = new String[9]; 
    String[] arrayAnsSet4 = new String[4]; 
    String[] arrayAnsSet5 = new String[4];
    String[] arrayAnsSet6 = new String[4]; 
    
    /**
     * Creates new form questionPage
     */
    public questionPage() {
        initComponents();
        
        arrayAnsSet1[0] = "1. Archaea";
        arrayAnsSet1[1] = "2. Bacteria";
        arrayAnsSet1[2] = "3. Eukaryota";
        
        arrayAnsSet2[0] = "1. Protista";
        arrayAnsSet2[1] = "2. Fungi";
        arrayAnsSet2[2] = "3. Plantae";
        arrayAnsSet2[3] = "4. Animalia";
        
        arrayAnsSet3[0] = "1. Porifera";
        arrayAnsSet3[1] = "2. Cnidaria";
        arrayAnsSet3[2] = "3. Rotifera";
        arrayAnsSet3[3] = "4. Platyhelminthes";
        arrayAnsSet3[4] = "5. Nematoda";
        arrayAnsSet3[5] = "6. Annelida";
        arrayAnsSet3[6] = "7. Mollusca";
        arrayAnsSet3[7] = "8. Echinodermata";
        arrayAnsSet3[8] = "9. Chordata";
        
        startUp();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        ans1Label = new javax.swing.JLabel();
        ans3Label = new javax.swing.JLabel();
        ans2Label = new javax.swing.JLabel();
        ans4Label = new javax.swing.JLabel();
        ans5Label = new javax.swing.JLabel();
        ans6Label = new javax.swing.JLabel();
        ans7Label = new javax.swing.JLabel();
        ans8Label = new javax.swing.JLabel();
        ans9Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ansBox = new javax.swing.JTextField();
        outputLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        nameLabel.setBackground(new java.awt.Color(0, 0, 0));
        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Banded Snail");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/culminating/project/Banded Snail.jpg"))); // NOI18N

        ans1Label.setBackground(new java.awt.Color(0, 0, 0));
        ans1Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans1Label.setForeground(new java.awt.Color(255, 255, 255));
        ans1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans3Label.setBackground(new java.awt.Color(0, 0, 0));
        ans3Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans3Label.setForeground(new java.awt.Color(255, 255, 255));
        ans3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans2Label.setBackground(new java.awt.Color(0, 0, 0));
        ans2Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans2Label.setForeground(new java.awt.Color(255, 255, 255));
        ans2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans4Label.setBackground(new java.awt.Color(0, 0, 0));
        ans4Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans4Label.setForeground(new java.awt.Color(255, 255, 255));
        ans4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans5Label.setBackground(new java.awt.Color(0, 0, 0));
        ans5Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans5Label.setForeground(new java.awt.Color(255, 255, 255));
        ans5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans6Label.setBackground(new java.awt.Color(0, 0, 0));
        ans6Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans6Label.setForeground(new java.awt.Color(255, 255, 255));
        ans6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans7Label.setBackground(new java.awt.Color(0, 0, 0));
        ans7Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans7Label.setForeground(new java.awt.Color(255, 255, 255));
        ans7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans8Label.setBackground(new java.awt.Color(0, 0, 0));
        ans8Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans8Label.setForeground(new java.awt.Color(255, 255, 255));
        ans8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ans9Label.setBackground(new java.awt.Color(0, 0, 0));
        ans9Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ans9Label.setForeground(new java.awt.Color(255, 255, 255));
        ans9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Answer Here");

        ansBox.setBackground(new java.awt.Color(0, 0, 0));
        ansBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ansBox.setForeground(new java.awt.Color(255, 255, 255));
        ansBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ansBox.setToolTipText("");
        ansBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBoxActionPerformed(evt);
            }
        });

        outputLabel.setBackground(new java.awt.Color(0, 0, 0));
        outputLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(255, 255, 255));
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        scoreLabel.setBackground(new java.awt.Color(0, 0, 0));
        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ansBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ans5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ans6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ans7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ans8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ans1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ans2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ans3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ans4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(ans9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ans9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ansBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBoxActionPerformed
        String answer; 
        answer = ansBox.getText(); 
        ansBox.setText("");

         switch (quesNum) {
            case 1:
                if (answer.equals("1")) { 
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Keep Trying!"); 
                    ans1Label.setText("");
                } else if (answer.equals("2")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Try again!");
                    ans4Label.setText("");
                } else if (answer.equals("3")) {
                    score++;
                    scoreLabel.setText("Score: " + score);
                    clearLabels();
                    quesNum++;
                    ans5Label.setText(arrayAnsSet2[0]);
                    ans6Label.setText(arrayAnsSet2[1]);
                    ans7Label.setText(arrayAnsSet2[2]);
                    ans8Label.setText(arrayAnsSet2[3]);
                } else {
                    outputLabel.setText("Please enter a number between 1-3 to answer.");
                }
                break;
                
                case 2:
                if (answer.equals("1")) { 
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Keep Trying!"); 
                    ans5Label.setText("");
                } else if (answer.equals("2")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Try again!");
                    ans6Label.setText("");
                } else if (answer.equals("3")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Keep going!");
                    ans7Label.setText("");                   
                }else if (answer.equals("4")) {
                    score++;
                    scoreLabel.setText("Score: " + score);
                    clearLabels();
                    quesNum++;
                    ans1Label.setText(arrayAnsSet3[0]);
                    ans2Label.setText(arrayAnsSet3[1]);
                    ans3Label.setText(arrayAnsSet3[2]);
                    ans4Label.setText(arrayAnsSet3[3]);
                    ans5Label.setText(arrayAnsSet3[4]);
                    ans6Label.setText(arrayAnsSet3[5]);
                    ans7Label.setText(arrayAnsSet3[6]);
                    ans8Label.setText(arrayAnsSet3[7]);
                    ans9Label.setText(arrayAnsSet3[8]);
                }else {
                    outputLabel.setText("Please enter a number between 1-4 to answer.");
                }
                break;
                
                case 3:
                if (answer.equals("1")) { 
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Keep Trying!"); 
                    ans1Label.setText("");
                } else if (answer.equals("2")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Try again!");
                    ans2Label.setText("");
                } else if (answer.equals("3")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Wrong! Keep going!");
                    ans3Label.setText("");                   
                }else if (answer.equals("4")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Take a breathe, you got this!");
                    ans4Label.setText("");                  
                }else if (answer.equals("5")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Close!");
                    ans5Label.setText("");
                }else if (answer.equals("6")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("Almost!");
                    ans6Label.setText("");
                }else if (answer.equals("7")) {
                    score++;
                    scoreLabel.setText("Score: " + score);
                    clearLabels();
                    quesNum++;
                    startUp();
                }else if (answer.equals("8")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("incorrect! But don't Stop!");
                    ans8Label.setText("");
                }else if (answer.equals("9")) {
                    score--;
                    scoreLabel.setText("Score: " + score);
                    outputLabel.setText("So close!");
                    ans9Label.setText("");
                }else {
                    outputLabel.setText("Please enter a number between 1-9 to answer.");
                }
                break;
         }
    }//GEN-LAST:event_ansBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new questionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ans1Label;
    private javax.swing.JLabel ans2Label;
    private javax.swing.JLabel ans3Label;
    private javax.swing.JLabel ans4Label;
    private javax.swing.JLabel ans5Label;
    private javax.swing.JLabel ans6Label;
    private javax.swing.JLabel ans7Label;
    private javax.swing.JLabel ans8Label;
    private javax.swing.JLabel ans9Label;
    private javax.swing.JTextField ansBox;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
